#!/usr/bin/php
<?php

    use mvc_framework\core\commands\Command;

    ini_set('display_errors', 'on');

    if(file_exists(__DIR__.'/core/autoload.php')) {
        require_once __DIR__.'/core/autoload.php';
    }
    require_once __DIR__.'/core/commands/Command.php';
	Command::clean_argv($argv);
	$command = new Command($argv);
	$command->execute();